description: 'Hacking & Development'
repoURL: 'https://github.com/jmau111/jmau111.github.io'
repoEditURL: 'https://github.com/jmau111/jmau111.github.io'
titleSeparator: ' ✭ '
icon: images/favicon-32x32.png
siteType: Person
publisherName: Julien Maury
publisherLogo: images/favicon-32x32.png
mainSections:
  - post
defaultImage: /images/default.jpg
